### ISSUE TITLE
threaded sum not optimal

### ISSUE THREAD

**Issue by SimonDanisch** [Jutho/Strided.jl#2]
Not sure if this is relevant for this package, but since I just recently implemented a threaded sum, this was the first I tested:

```Julia
function threadsum(x::AbstractArray{T}) where T
    M = length(x)
    N = Threads.nthreads()
    result = similar(x, N)
    @inbounds Threads.@threads for t = 1:N
        accum = zero(T)
        @simd for i = round(Int, M*(t-1)/N)+1:round(Int, M*t/N)
            accum += x[i]
        end
        result[t] = accum
    end
    sum(result)
end

Threads.nthreads()
 12

x = rand(10^7)
@btime @strided sum($x)
 9.357 ms (1 allocation: 48 bytes)
@btime sum($x)
  3.449 ms (0 allocations: 0 bytes)
@btime threadsum($x)
  2.562 ms (3 allocations: 272 bytes)
```
(threadsum implementation improved by @maxbennedich)

Probably just needs some specialization to make the simple cases fast?

**Comment by Jutho** [comment]
I think the problem is that a complete `(map)reduce`, i.e. not a partial reduction with a `dims` keyword argument, is currently not overloaded in my package. I only provided an implementation for `Base.mapreducedim!`, but a complete reduction doesn't pass via that function. Something I probably needed to add before announcing the package. I'll try to fix asap. But even then, there might still be a bit of overhead.

**Comment by SimonDanisch** [comment]
Ah no worries, I don't really need it yet :) Just thought you might be interested in this with a reference implementation!

**Comment by Jutho** [comment]
There is anyway something going wrong with reductions, it seems. I'll have to investigate further.

**Comment by GiggleLiu** [comment]
Maybe a related performance issue, The following is the example in the README of https://github.com/oschulz/UnsafeArrays.jl
```
julia> @benchmark colnorms!(dest, A)
BenchmarkTools.Trial: 
  memory estimate:  4.58 MiB
  allocs estimate:  100001
  --------------
  minimum time:     4.962 ms (0.00% GC)
  median time:      5.345 ms (0.00% GC)
  mean time:        5.869 ms (8.04% GC)
  maximum time:     10.864 ms (36.38% GC)
  --------------
  samples:          850
  evals/sample:     1

julia> @benchmark @uviews A begin
           colnorms!(dest, A)
       end
BenchmarkTools.Trial: 
  memory estimate:  80 bytes
  allocs estimate:  2
  --------------
  minimum time:     4.337 ms (0.00% GC)
  median time:      4.534 ms (0.00% GC)
  mean time:        4.645 ms (0.00% GC)
  maximum time:     7.797 ms (0.00% GC)
  --------------
  samples:          1074
  evals/sample:     1

julia> @benchmark @unsafe_strided A colnorms!(dest, A)
BenchmarkTools.Trial: 
  memory estimate:  144 bytes
  allocs estimate:  2
  --------------
  minimum time:     21.968 ms (0.00% GC)
  median time:      22.184 ms (0.00% GC)
  mean time:        22.252 ms (0.00% GC)
  maximum time:     26.514 ms (0.00% GC)
  --------------
  samples:          225
  evals/sample:     1
```

**Comment by GiggleLiu** [comment]
Maybe a related performence issue. This is the example in https://github.com/oschulz/UnsafeArrays.jl
```julia console
julia> @benchmark @uviews A begin
           colnorms!(dest, A)
       end
BenchmarkTools.Trial: 
  memory estimate:  80 bytes
  allocs estimate:  2
  --------------
  minimum time:     4.329 ms (0.00% GC)
  median time:      4.480 ms (0.00% GC)
  mean time:        4.516 ms (0.00% GC)
  maximum time:     7.140 ms (0.00% GC)
  --------------
  samples:          1105
  evals/sample:     1

julia> @benchmark @unsafe_strided A colnorms!(dest, A)
BenchmarkTools.Trial: 
  memory estimate:  144 bytes
  allocs estimate:  2
  --------------
  minimum time:     21.993 ms (0.00% GC)
  median time:      22.323 ms (0.00% GC)
  mean time:        22.480 ms (0.00% GC)
  maximum time:     28.258 ms (0.00% GC)
  --------------
  samples:          223
  evals/sample:     1
```

**Comment by Jutho** [comment]
@GiggleLiu , that's a different problem. Consider this:

```julia
using UnsafeArrays, Strided, BenchmarkTools, LinearAlgebra

A = randn(100,100);
B = Strided.UnsafeStridedView(A);
C = UnsafeArray(pointer(A), size(A));
@btime norm($A) #:   3.077 μs (0 allocations: 0 bytes)
@btime norm($B) #:   43.699 μs (0 allocations: 0 bytes)
@btime norm($C) #:   33.559 μs (0 allocations: 0 bytes)
A = randn(10000);
B = Strided.UnsafeStridedView(A);
C = UnsafeArray(pointer(A), size(A));
@btime norm($A) #:   3.083 μs (0 allocations: 0 bytes)
@btime norm($B) #:   32.349 μs (0 allocations: 0 bytes)
@btime norm($C) #:   3.082 μs (0 allocations: 0 bytes)
```
In the vector case (the second case), `A` and `C` end up calling BLAS (check `@which LinearAlgebra.norm2(A) # or B or C`, `norm2` is what ends up being called)`. For `B`, this does not happen, because `(Unsafe)StridedView` is not `<:DenseArray`, whereas `UnsafeArray` is.

In the matrix case (or for any `ndims>1`), only `A`, the pure `Array` is dispatched to BLAS. Both `B` and `C` fall back to the generic Julia implementation of `norm2`. Here, the difference between `B` and `C` is likely due to `C` being `IndexLinear()`, whereas `B` being `IndexCartesian()`.

**Comment by Jutho** [comment]
With Strided v0.2.0 (just released), I now have:
With `Threads.nthreads() == 1`:
```julia
julia> @btime @strided sum($x)
  4.503 ms (13 allocations: 480 bytes)

julia> @btime sum($x)
  4.461 ms (0 allocations: 0 bytes)

julia> @btime threadsum($x)
  11.450 ms (2 allocations: 160 bytes)
```
and with `Threads.nthreads() == 4`
```
julia> @btime @strided sum($x)
  3.010 ms (97 allocations: 2.95 KiB)

julia> @btime sum($x)
  4.462 ms (0 allocations: 0 bytes)

julia> @btime threadsum($x)
  3.170 ms (2 allocations: 176 bytes)
```
I think this closes this issue ?

However, I hope there are no bugs in the newly added support for complete reductions, as getting the initializations correctly is certainly not entirely trivial.

**Comment by SimonDanisch** [comment]
That's great to see :)

**Comment by SimonDanisch** [comment]
Btw, would you like to open up the scope of this package? I've a couple of lazy broadcast constructs + multi threading that are looking for a new home^^

**Comment by Jutho** [comment]
Such as? There is not that much lazy in this package, except for the fact that `permutedims` acts lazily, i.e. produces a view. But mostly this is about cache friendly blocking strategies for simultaneously looping over several multidimensional arrays. But in principle, yes, I am certainly open to contributions along those lines.

**Comment by Jutho** [comment]
Is `@lazy` just creating the `Broadcasted` struct without actually materializing it. In principle, this would work well with Strided.jl. 

The crux of Strided.jl is in the file `mapreduce.jl`, which contains an implementation of `Base.mapreducedim!` but which is much more general. Actually, the most general entry point is `Strided._mapreducedim!` which takes as input
* a set of arrays, the first of which is the output array, and the others are one or more input arrays, where the different arrays can have for either size one or a matching size along every dimension. Also the output array can have size one along one or more dimensions, in which case a reduction is performed.
* a map `f`, which can be multi-argument map taking in several values, i.e. the elements of the input arrays are fed into `f`
* a reduction operator `op`
* an initialization operator `initop`, which is applied to all the entries of the output array when they are first visited.

This functionality goes strictly beyond the union of Julia Base's broadcasting (which only broadcasts input arrays, but does not perform reductions before creating the output array) and `mapreduce`, which only accepts a single input array and an initial value (instead of an `initop`).
